### ISSUE TITLE
Frozen requirements.txt breaks other plugins

### ISSUE THREAD

**Issue by Dreamsorcerer** [Tadaboody/good_smell#65]
If I install a set of requirements that includes for example:
```
good-smell
wemake-python-styleguide
```

Then good-smell forces specific version numbers in its dependencies, which results in breaking other projects which require newer releases. In this example, good-smell installs astor 0.7.1, but wemake will error without version >=0.8.

A more flexible requirements.txt would be nice to have here. In this case, I see no errors after forcing astor to upgrade to the latest 0.8.1 release.

**Comment by Tadaboody** [comment]
Hey, thanks for all the issues! Sadly couldn't get around to it this weekend, but I'll take care of it. Feel free to open a PR as well ^_^

**Comment by Tadaboody** [comment]
Hey, so the `requirements.txt` shouldn't have been in the repository, because it uses [pipenv](https://github.com/pypa/pipenv) for package managment. If you're trying to install from source check out the contributing guide!

**Comment by Dreamsorcerer** [comment]
Hey, sorry, I am installing through pip. i.e. With the 2 lines in my original comment in a requirements.txt file, if I `pip install -r requirements.txt` then I encounter that problem.

I merely mentioned the requirements.txt file in the repo as it appears to match the versions that are getting required when installing via pip.

**Comment by Tadaboody** [comment]
Oh sorry I didn't completely get what you meant, will try and fix it now!

**Comment by Tadaboody** [comment]
Removed the lockfile and fixed it - please try it and tell me if it isn't fixed on your end

**Comment by Dreamsorcerer** [comment]
Didn't get any warnings when doing an upgrade. So, looks good to me.
